[versions]
agp = "8.13.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-espresso = "3.7.0"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.3.0"
composeHotReload = "1.0.0-rc03"
composeMultiplatform = "1.9.3"
exposedCore = "0.61.0"
exposedCoreVersion = "0.56.0"
exposedDao = "0.56.0"
exposedJdbc = "0.56.0"
h2 = "2.2.224"
hikaricp = "7.0.2"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
ktor = "3.3.2"
ktorSerializationKotlinxJsonJvm = "3.3.2"
ktorSerializationKotlinxJsonJvmVersion = "3.0.0"
ktorServerAuthJvm = "3.3.2"
ktorServerAuthJwtJvm = "3.3.2"
ktorServerContentNegotiationJvm = "3.3.2"
ktorServerContentNegotiationJvmVersion = "3.0.0"
ktorServerCoreJvm = "3.0.0"
ktorServerNettyJvm = "3.0.0"
logback = "1.5.20"
kotlinxCoroutinesVersion = "1.10.2"
postgresql = "42.7.8"
bcrypt = "0.10.2"

[libraries]
bcrypt = { group = "at.favre.lib", name = "bcrypt", version.ref = "bcrypt" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposedCore" }
exposed-core-v0560 = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposedCoreVersion" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposedCore" }
exposed-dao-v0560 = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposedDao" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposedCore" }
exposed-jdbc-v0560 = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposedJdbc" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesVersion" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
ktor-serialization-kotlinx-json-jvm = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktorSerializationKotlinxJsonJvm" }
ktor-serialization-kotlinx-json-jvm-v300 = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktorSerializationKotlinxJsonJvmVersion" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jvm = { module = "io.ktor:ktor-server-auth-jvm", version.ref = "ktorServerAuthJvm" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-auth-jwt-jvm = { module = "io.ktor:ktor-server-auth-jwt-jvm", version.ref = "ktorServerAuthJwtJvm" }
ktor-server-content-negotiation-jvm = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktorServerContentNegotiationJvm" }
ktor-server-content-negotiation-jvm-v300 = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktorServerContentNegotiationJvmVersion" }
ktor-server-core-jvm-v300 = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktorServerCoreJvm" }
ktor-server-netty-jvm-v300 = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktorServerNettyJvm" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-serverCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-serverNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serverTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
ktor-server-error-handler = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }